# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marko Knežević
email: imi.knezevic@gmail.com
description: >
  Sajt koji sadrži lekcije raznih kurseva.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://knezevicmarko.github.io/" # the base hostname & protocol for your site

# Build settings
sass:
  sass_dir: _sass
indlude: ['_pages']
highlighter: rouge
markdown: kramdown
excerpt_separator: ""

collections:
  os1:
    title: Operativni sistemi 1
    output: true
    image: os1.png
    description:
      Uvod u operativne sisteme. Hardverski i softverski koncepti. Koncepti procesa. Asinhrono konkurentno izvođenje. Konkurentno programiranje. Zastoj i neodređeno odlaganje. Vremensko planiranje procesa. Organizacija realne memorije i upravljanje. Organizacija virtualne memorije. Upravljanje bitruelnom memorijom. Optimizacija performansi diska. Sistemi podataka i datoteka.
  os2:
    title: Operativni sistemi 2
    output: true
    image: os2.png
    description:
      Upravljanje ulazno/izlaznim uređajima i raspoređivanje diska. Fajl sistemi. Jednoprocesorsko raspoređivanje (scheduling). Višeprocesorsko raspoređivanje i raspođivanje u realnom vremenu. Distribuirani sistemi, klijent/serveri i klasteri. Grid računarstvo. Sigurnost i bezbednost računarskih sistema.
